VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISort"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'---------交换------------
Function Swap(i As Long, j As Long)

End Function

'---------赋值------------
'将第j个赋值给第i个
Function Assignment(i As Long, j As Long)

End Function
'将Value赋值给第i个
Function AssignmentValue(i As Long, Value)

End Function
'将第i个赋值给Value
Function ReAssignmentValue(i As Long, Value)

End Function

'---------比较------------
'第i个是否小于第j个
Function Less(i As Long, j As Long) As Boolean

End Function
'第i个是否小于Value
Function LessValue(i As Long, Value) As Boolean

End Function
'第i个是否大于Value
Function LagerValue(i As Long, Value) As Boolean

End Function

'---------其他------------
'三数取中
Function MedianOfThree(ByVal Low As Long, ByVal High As Long)

End Function
